// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using System;

namespace DiscountManagement.Infrastructure.EFCore.Migrations;

[DbContext(typeof(DiscountDbContext))]
internal partial class DiscountDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.17")
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        modelBuilder.Entity("DiscountManagement.Domain.ColleagueDiscountAggregate.ColleagueDiscount", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreationDate")
                    .HasColumnType("datetime2");

                b.Property<int>("DiscountRate")
                    .HasColumnType("int");

                b.Property<bool>("IsRemoved")
                    .HasColumnType("bit");

                b.Property<long>("ProductId")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("ColleagueDiscounts");
            });

        modelBuilder.Entity("DiscountManagement.Domain.CustomerDiscountAggregate.CustomerDiscount", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreationDate")
                    .HasColumnType("datetime2");

                b.Property<int>("DiscountRate")
                    .HasColumnType("int");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<long>("ProductId")
                    .HasColumnType("bigint");

                b.Property<string>("Reason")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("CustomerDiscounts");
            });
    }
}
